### ISSUE TITLE
Installing with brew fails on macOS 10.12.6 (Sierra)

### ISSUE THREAD

**Issue by niclasek** [vpn-kill-switch/homebrew-killswitch#1]
Hi, I think you have created a great tool and I would like to use it. However when I install it I get the following error:

brew install killswitch
==> Installing killswitch from vpn-kill-switch/killswitch
==> Downloading https://homebrew.bintray.com/bottles-killswitch/killswitch-0.4.2.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "killswitch"
Download failed: https://homebrew.bintray.com/bottles-killswitch/killswitch-0.4.2.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/vpn-kill-switch/killswitch.git
Updating /Users/niclas/Library/Caches/Homebrew/killswitch--git
==> Checking out tag 0.4.2
Error: 0.4.2 tag should be 763f87a995141fef1372dd8dff8f57ee28baeded
but is actually 4eb3b3f94a22b713d96aa376249d9b563d97051a

**Comment by Rod-Persky** [comment]
@niclasek you may edit the brew file using

`brew edit killswitch`

Find the quoted text that reads baeded and replace it with the new checksum. Otherwise I expect the pull request will fix this issue.
